# Generated by Django 2.0.5 on 2018-05-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dno', models.IntegerField(primary_key=True, serialize=False, verbose_name='部门编号')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('location', models.CharField(max_length=10, verbose_name='部门地点')),
                ('excellent', models.BooleanField(default=0, verbose_name='是否优秀')),
            ],
            options={
                'db_table': 'tb_dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='员工编号')),
                ('name', models.CharField(max_length=20, verbose_name='员工姓名')),
                ('job', models.CharField(max_length=10, verbose_name='职位')),
                ('mar', models.CharField(blank=True, max_length=20, null=True, verbose_name='主管')),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='工资')),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='补贴')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrs.Dept')),
            ],
            options={
                'db_table': 'tb_emp',
            },
        ),
    ]
