# Generated by Django 2.0.5 on 2018-05-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_img',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
