# Generated by Django 2.0.5 on 2018-05-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_s_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_chinese',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='s_math',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
