# Generated by Django 2.0.5 on 2018-05-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180530_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_addr', models.CharField(max_length=30)),
                ('stu_age', models.IntegerField()),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='s_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='s_sex',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='s_tel',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_chinese',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_math',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='stu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
