# Generated by Django 2.0.5 on 2018-05-31 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180530_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_sex',
            new_name='delete',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_tel',
        ),
    ]
