# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180523_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carno', models.CharField(max_length=7)),
                ('reason', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, db_column='happen_date')),
                ('punish', models.CharField(max_length=50)),
                ('isdone', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_car_record',
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
