# Generated by Django 2.0.5 on 2018-05-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
